#!/usr/bin/env bash

make test_comm

mpirun -np 2  -hostfile ../hosts ./test_comm 1000
mpirun -np 4  -hostfile ../hosts ./test_comm 1000
mpirun -np 8  -hostfile ../hosts ./test_comm 1000
mpirun -np 16 -hostfile ../hosts ./test_comm 1000
